In [3]:
import numpy as np
a=np.array([[1,2,3],[0,1,4],[4,1,2]])
print(a)
print(a.min(axis=0))
print(a.max(axis=0))

[[1 2 3]
 [0 1 4]
 [4 1 2]]
[1 0 1]
[3 4 4]


In [3]:
import numpy as np
idx=np.arange(10)
print(idx)
np.random.shuffle(idx)
print(idx)

[0 1 2 3 4 5 6 7 8 9]
[2 7 4 0 9 8 6 1 3 5]


In [3]:
import numpy as np
x=np.array([1,2,3])
print(x.shape[1] if len(x)==2 else x.shape[0])

3


In [2]:
center=np.array([0.5,1,2])
print(a-center)

[[ 0.5  1.   1. ]
 [-0.5  0.   2. ]
 [ 3.5  0.   0. ]]


In [5]:
label=np.array([0,1,0])
a[label==1]

array([[0, 1, 4]])

In [5]:
import numpy as np 
a=np.array([[1,2,3,4],[6,7,8,9]])
b=np.zeros((2,4))
b[1,:]=a[1]
a[1,:]=10
print(b)

[[0. 0. 0. 0.]
 [6. 7. 8. 9.]]
