### Linear Regression using OLS

In [1]:
import numpy as np 
import pandas as pd 
# load the data, all the data files are in ./data/
df=pd.read_excel("data/real_estate.xlsx",header=0,index_col=None)
df["view"]=df["view"].map({"No sea view":0.0,"Sea view":1.0})
print(df.head())

        price     size  year  view
0  234314.144   643.09  2015   0.0
1  228581.528   656.22  2009   0.0
2  281626.336   487.29  2018   1.0
3  401255.608  1504.75  2015   0.0
4  458674.256  1275.46  2009   1.0


In [2]:
X_org=df.iloc[:,1:].values
y_org=df.price.values
print(X_org.shape)
print(y_org.shape)

(100, 3)
(100,)


In [3]:
from myML.MLR import linear_regression_OLS
lr=linear_regression_OLS()
lr.train(X_org,y_org)
lr.print_coef()

[-5.39791418e+06  2.23031619e+02  2.71894889e+03  5.67260198e+04]


In [4]:
x_predict=np.array([[700,2015,0],[600,2014,1]])
print(lr.predict(x_predict))

[236889.96264513 268593.87161053]


### Linear Regression using SGD

In [1]:
import numpy as np 
import pandas as pd 
# load the data, all the data files are in ./data/
df=pd.read_excel("data/real_estate.xlsx",header=0,index_col=None)
df["view"]=df["view"].map({"No sea view":0.0,"Sea view":1.0})
print(df.head())
X_org=df.iloc[:,1:].values
y_org=df.price.values
print(X_org.shape)
print(y_org.shape)
from myML.MLR import linear_regression_SGD
lr=linear_regression_SGD(eta=10,tol=0.01,max_iter=10)
lr.train(X_org,y_org)
lr.print_coef()

        price     size  year  view
0  234314.144   643.09  2015   0.0
1  228581.528   656.22  2009   0.0
2  281626.336   487.29  2018   1.0
3  401255.608  1504.75  2015   0.0
4  458674.256  1275.46  2009   1.0
(100, 3)
(100,)
[-3.37052130e+75 -2.35430910e+78 -6.79160043e+78  6.87352327e+67]


In [4]:
X_org[50,:]

array([ 647.5, 2015. ,    0. ])